// NEON blitter for display
// Generated by Claude Sonnet 4.6

#include <arm_neon.h>
#include <stdint.h>

/* Phase 1: RGBA -> RGB565, 8 pixels at a time.
 * vld4_u8 deinterleaves the four channels for free. */
void rgba_to_rgb565(const uint8_t* src, uint16_t* dst, int n) {
    for (; n >= 8; n -= 8, src += 32, dst += 8) {
        uint8x8x4_t px = vld4_u8(src);

        uint16x8_t r = vshlq_n_u16(vmovl_u8(vshr_n_u8(px.val[0], 3)), 11);
        uint16x8_t g = vshlq_n_u16(vmovl_u8(vshr_n_u8(px.val[1], 2)),  5);
        uint16x8_t b =             vmovl_u8(vshr_n_u8(px.val[2], 3));

        vst1q_u16(dst, vorrq_u16(vorrq_u16(r, g), b));
    }
    /* scalar tail for any remainder */
    for (; n > 0; n--, src += 4, dst++)
        *dst = ((uint16_t)(src[0] >> 3) << 11)
             | ((uint16_t)(src[1] >> 2) <<  5)
             |  (uint16_t)(src[2] >> 3);
}

/* Transpose one 8×8 block of uint16.
 * src_stride: row stride in src (elements, not bytes).
 * dst_stride: column stride in dst — negative for reversed-column layout. */
static inline void transpose_8x8(
    const uint16_t* src, int src_stride,
          uint16_t* dst, int dst_stride)
{
    uint16x8_t r0 = vld1q_u16(src + 0 * src_stride);
    uint16x8_t r1 = vld1q_u16(src + 1 * src_stride);
    uint16x8_t r2 = vld1q_u16(src + 2 * src_stride);
    uint16x8_t r3 = vld1q_u16(src + 3 * src_stride);
    uint16x8_t r4 = vld1q_u16(src + 4 * src_stride);
    uint16x8_t r5 = vld1q_u16(src + 5 * src_stride);
    uint16x8_t r6 = vld1q_u16(src + 6 * src_stride);
    uint16x8_t r7 = vld1q_u16(src + 7 * src_stride);

    /* Round 1: interleave adjacent pairs of u16 */
    uint16x8x2_t q01 = vtrnq_u16(r0, r1);
    uint16x8x2_t q23 = vtrnq_u16(r2, r3);
    uint16x8x2_t q45 = vtrnq_u16(r4, r5);
    uint16x8x2_t q67 = vtrnq_u16(r6, r7);

    /* Round 2: interleave 2×2 blocks via u32 reinterpret */
    uint32x4x2_t q0123e = vtrnq_u32(vreinterpretq_u32_u16(q01.val[0]),
                                     vreinterpretq_u32_u16(q23.val[0]));
    uint32x4x2_t q0123o = vtrnq_u32(vreinterpretq_u32_u16(q01.val[1]),
                                     vreinterpretq_u32_u16(q23.val[1]));
    uint32x4x2_t q4567e = vtrnq_u32(vreinterpretq_u32_u16(q45.val[0]),
                                     vreinterpretq_u32_u16(q67.val[0]));
    uint32x4x2_t q4567o = vtrnq_u32(vreinterpretq_u32_u16(q45.val[1]),
                                     vreinterpretq_u32_u16(q67.val[1]));

    /* Round 3: combine low/high halves across the 4×4 boundary.
     * (vtrnq_u64 is AArch64 only; use vcombine+vget_low/high on AArch32) */
#define LHCOMBINE(a, b) \
    vcombine_u16(vget_low_u16(vreinterpretq_u16_u32(a)), \
                 vget_low_u16(vreinterpretq_u16_u32(b)))
#define HHCOMBINE(a, b) \
    vcombine_u16(vget_high_u16(vreinterpretq_u16_u32(a)), \
                 vget_high_u16(vreinterpretq_u16_u32(b)))

    uint16x8_t o0 = LHCOMBINE(q0123e.val[0], q4567e.val[0]);
    uint16x8_t o1 = LHCOMBINE(q0123o.val[0], q4567o.val[0]);
    uint16x8_t o2 = LHCOMBINE(q0123e.val[1], q4567e.val[1]);
    uint16x8_t o3 = LHCOMBINE(q0123o.val[1], q4567o.val[1]);
    uint16x8_t o4 = HHCOMBINE(q0123e.val[0], q4567e.val[0]);
    uint16x8_t o5 = HHCOMBINE(q0123o.val[0], q4567o.val[0]);
    uint16x8_t o6 = HHCOMBINE(q0123e.val[1], q4567e.val[1]);
    uint16x8_t o7 = HHCOMBINE(q0123o.val[1], q4567o.val[1]);

#undef LHCOMBINE
#undef HHCOMBINE

    vst1q_u16(dst + 0 * dst_stride, o0);
    vst1q_u16(dst + 1 * dst_stride, o1);
    vst1q_u16(dst + 2 * dst_stride, o2);
    vst1q_u16(dst + 3 * dst_stride, o3);
    vst1q_u16(dst + 4 * dst_stride, o4);
    vst1q_u16(dst + 5 * dst_stride, o5);
    vst1q_u16(dst + 6 * dst_stride, o6);
    vst1q_u16(dst + 7 * dst_stride, o7);
}

/*
 * blit_transposed — rotate a landscape RGB565 buffer 90° CW into a portrait
 * framebuffer using tiled 8×8 NEON transposes.
 *
 * src:        row-major [src_height][src_width]   (e.g. 240 rows × 320 cols)
 * dst:        framebuffer, row-major portrait      (e.g. 320 rows × 240 cols)
 *
 * Pixel mapping:
 *   src(lx, ly)  →  dst[(src_width - 1 - lx) * src_height + ly]
 *
 * For a 320×240 source writing into a 240×320 framebuffer:
 *   dst[(319 - lx) * 240 + ly]
 *
 * Both src_width and src_height must be multiples of 8.
 */
void blit_transposed(const uint16_t* src, uint16_t* dst,
                     int src_width, int src_height)
{
    for (int ty = 0; ty < src_height; ty += 8) {
        for (int tx = 0; tx < src_width; tx += 8) {
            const uint16_t* s = src + ty * src_width + tx;

            /* dst base for this tile: (src_width-1-tx)*src_height + ty
             * dst_stride: step when tx increases by 1 = -src_height
             * (columns run in reverse order in the framebuffer) */
            uint16_t* d = dst + (src_width - 1 - tx) * src_height + ty;

            transpose_8x8(s, src_width, d, -src_height);
        }
    }
}
